-- Phase 2: Smart Coach Ecosystem Schema
-- Based on SMART_SYSTEM_PLAN.md

-- 1. SAVED ROUTINES (The Master Plan)
-- Stores the generated or custom routines.
create table if not exists public.saved_routines (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    is_active boolean default false, -- Only one active routine per user usually
    
    -- The Inputs used to generate this (for re-generation/adaptation)
    configuration jsonb not null default '{}'::jsonb, 
    -- Example: { "goal": "hypertrophy", "level": "intermediate", "equipment": ["dumbbell", "bench"] }

    -- The Routine Structure (The Recipe)
    schedule jsonb not null default '{}'::jsonb,
    -- Example: { "days": [ { "name": "Push A", "exercises": [...] } ] }

    -- Intelligent Metabolic Data
    estimated_calories_per_session jsonb default '{}'::jsonb,
    
    -- Current Progression State (Phase 1 of 4, etc.)
    brain_state jsonb default '{}'::jsonb
);

-- 2. USER SCHEDULE (The Calendar)
-- Maps specific routine days to real-world week days.
create table if not exists public.user_schedule (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    day_of_week integer not null check (day_of_week between 0 and 6), -- 0=Sunday, 1=Monday...
    time_slot text check (time_slot in ('morning', 'afternoon', 'night')),
    
    -- Links to a specific 'day' within the saved_routine structure
    -- We store the routine_id and the day_index/id from the JSON
    saved_routine_id bigint references public.saved_routines(id) on delete cascade,
    routine_day_id text -- Acts as a pointer to the day inside the JSON (e.g., "push_a")
);

-- 3. WORKOUT LOGS (The Evidence)
-- Detailed logs for every session.
create table if not exists public.workout_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    exercise_id bigint references public.exercises(id),
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- The Core Metric for Progression
    -- Structure: [{ "set": 1, "weight": 50, "reps": 10, "rir": 2 }, ...]
    sets_data jsonb not null default '[]'::jsonb,
    
    -- Subjetive Feedback
    rpe_rating integer check (rpe_rating between 1 and 10), -- Overall session intensity
    performance_rating integer check (performance_rating between 1 and 5), -- How did you feel?
    notes text
);

-- 4. USER PROGRESSION (The Long-term Memory)
-- Tracks 1RM and volume history per exercise to inform the Brain.
create table if not exists public.user_progression (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    exercise_id bigint references public.exercises(id),
    
    estimated_1rm numeric,
    last_successful_weight numeric,
    last_updated timestamp with time zone default timezone('utc'::text, now()),
    
    -- To detect stalls
    consecutive_failures integer default 0
);

-- Enable RLS
alter table public.saved_routines enable row level security;
alter table public.user_schedule enable row level security;
alter table public.workout_logs enable row level security;
alter table public.user_progression enable row level security;

-- Policies (Standard User Access)
create policy "Users can view their own routines" on public.saved_routines for select using (auth.uid() = user_id);
create policy "Users can insert their own routines" on public.saved_routines for insert with check (auth.uid() = user_id);
create policy "Users can update their own routines" on public.saved_routines for update using (auth.uid() = user_id);

create policy "Users can view their own schedule" on public.user_schedule for select using (auth.uid() = user_id);
create policy "Users can manage their own schedule" on public.user_schedule for all using (auth.uid() = user_id);

create policy "Users can view their own logs" on public.workout_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own logs" on public.workout_logs for insert with check (auth.uid() = user_id);

create policy "Users can view their own progression" on public.user_progression for select using (auth.uid() = user_id);
create policy "Users can manage their own progression" on public.user_progression for all using (auth.uid() = user_id);
